theme: jekyll-theme-slate
title: MRI Together
description: A global workshop on Open Science and Reproducible MR Research

repository: mritogether/mritogether.github.io

plugins:
- jekyll-github-metadata
- jekyll-mentions
- jekyll-redirect-from
- jekyll-sitemap
- jemoji

header:
  links:
    - label: Home
      url: /
    - label: Program
      url: /program
    - label: Contact
      url: /contact
