theme: jekyll-theme-slate
title: MRI Together

repository: mritogether/mritogether.github.io

plugins:
- jekyll-github-metadata
- jekyll-mentions
- jekyll-redirect-from
- jekyll-sitemap
- jemoji

header:
  links:
    - label: Home
      url: /
