theme: jekyll-theme-slate
title: MRI Together
description: A global workshop on Open Science and Reproducible MR Research
email: mritogether.workshop@gmail.com

repository: mritogether/mritogether.github.io
markdown: kramdown

plugins:
- jekyll-github-metadata
- jekyll-mentions
- jekyll-redirect-from
- jekyll-sitemap
- jemoji

header:
  links:
    - label: Home
      url: /
    - label: Overview
      url: /overview
    - label: Program
      url: /timetable
    - label: Registration
      url: /registration
    - label: Accepted abstracts
      url: /abstracts
    - label: Organizers
      url: /committee
    - label: Sponsors
      url: /sponsors
    
